apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: monitoring
    user: user
    secureJsonData:
      password: password
    jsonData:
      sslmode: "disable"
      postgresVersion: 1200
      timescaledb: false
