apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: user
    database: monitoring
    password: password
    jsonData:
      sslmode: "disable"
      maxOpenConns: 50
      maxIdleConns: 50
      connMaxLifetime: 14400
      timescaledb: false
    isDefault: true
