name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Rodar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Verificar versão do Python
        run: python --version  # Apenas para confirmar que estamos na versão correta

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verificar instalação do pytest
        run: |
          python -m pytest tests/

      - name: Rodar testes
        run: |
          python -m pytest tests/
