name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Rodar Testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.4'

      - name: Instalar dependências
        run: |
          python -m pip install -r requirements.txt

      - name: Rodar testes
        run: |
          pytest tests/

  build-and-push:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        run: |
          docker build -t moa-fernandes/monitoring-agent:latest .

      - name: Push da imagem para o Docker Hub
        run: |
          docker push moa-fernandes/monitoring-agent:latest

  deploy:
    name: Deploy com Docker Compose
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
